### Recuperar todo
GET https://rest-api-node-4ufv.onrender.com/movies

### Recuperar por id
GET https://rest-api-node-4ufv.onrender.com/movies/9a043e1a-d6ef-11ef-83df-cecd02c24f20

### Recuperar por genero
GET https://rest-api-node-4ufv.onrender.com/movies?genre=drama


### Crear una pelicula con POST
POST  https://rest-api-node-4ufv.onrender.com/movies
Content-Type: application/json

{
    "title": "prueba final xd",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Fantasy"
    ],
    "rate": 0.5
}


### Actualizar una pelicula por id
PATCH https://rest-api-node-4ufv.onrender.com/movies/c5c58cfb-d617-11ef-b43f-cecd02c24f20
Content-Type: application/json

{
    "year": 2024
}


### delete
DELETE https://rest-api-node-4ufv.onrender.com/movies/3f543f89-d6f0-11ef-83df-cecd02c24f20